version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: svn co --quiet https://develop.svn.wordpress.org/tags/5.3/tests/phpunit/data/ /tmp/wordpress-tests-lib/data
      - run: svn co --quiet https://develop.svn.wordpress.org/tags/5.3/tests/phpunit/includes/ /tmp/wordpress-tests-lib/includes