version: 2.1

parameters:
  timestamp:
    type: datetime
    default: CURRENT_TIMESTAMP

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: node --version
      - run: echo $timestamp