version: 2.0
jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: svn co --quiet https://develop.svn.wordpress.org/tags/5.3/tests/phpunit/includes/ /tmp/wordpress-tests-lib/includes
      - run: svn co --quiet https://develop.svn.wordpress.org/tags/5.3/tests/phpunit/data/ /tmp/wordpress-tests-lib/data

workflow:
  version: 2
  custom-workflow:
    jobs:
      - test
