
version: 2
executors:
  node-exe:
    docker:
      - image: circleci/node:11.1.0

orbs:
  slack: circleci/slack@3.3.0

jobs:
  npm_build:
    executor: node-exe
    steps:
      - checkout
      - run: npm run build
  npm_succ:
    executor: node-exe
    steps:
      - run: echo "successful"
  npm_test:
    executor: node-exe
    steps:
      - checkout
      - run: npm run test
      - slack/status:
          fail_only: true
          mentions: 'USERID1,USERID2'
          only_for_branches: only_for_branches
          webhook: webhook

workflows:
  version: 2
  build_and_test:
    jobs:
      - npm_test