# version: 2.1

# # What I want to be able to do is
# # call \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat\" -host_arch=amd64 -arch=amd64
# # Which works fine on azure pipelines and over ssh

# orbs:
#   win: circleci/windows@1.0.0

# jobs:
#   installation:
#     docker:
#       - image: win/vs2019
    # steps:
    #   - run:
    #       name: install dotnet
    #       command: |
    #         sudo choco install powershell-core
    #         $PSVersionTable
    #   - run:
    #       name: install dotnet
    #       command: |
    #         sudo choco install dotnetcore-sdk
    #         dotnet --info

# workflows:
#   version: 2
#   build_and_test_all:
#     jobs:
#       - installation

version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: cmd.exe
    steps:
      - run:
          name: can we use dism?
          command: Dism /online /Get-Features
      - run:
          name: Don't know but installing something
          command: dism /online /Enable-Feature /Featurename:NetFX3 /All
      
      - run:
          name: install dependency
          command: choco install -y wixtoolset --version 3.11.0.20170506 

      - run:
          name: choco install awscli
          command: choco install awscli

    # OK just go away this is not working
      # - run:
      #     name: install powershell 6
      #     command: |
      #       choco install powershell-core
      # - run:
      #     name: set PATH
      #     command: |
      #       echo %PATH%
      # - run:
      #     name: check powershell version
      #     shell: "%PROGRAMFILES%\PowerShell\6\pwsh.exe"
      #     command: |
      #       $PSVersionTable.PSVersion
      # - run:
      #     name: install dotnet
      #     command: |
      #       choco upgrade dotnetcore-sdk
      # - run:
      #     name: check dotnet version
      #     command: |
      #       dotnet --info