version: 2.1

parameters:
  timestamp:
    type: datetime
    default: CURRENT_TIMESTAMP

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: node --version
      - run: svn co --quiet https://develop.svn.wordpress.org/tags/5.3/tests/phpunit/includes/ /tmp/wordpress-tests-lib/includes