version: 2.1
parameters:
  build_and_deploy:
    type: boolean
    default: true
workflows:
  version: 2
  test:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: circleci/node:11.1.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: store env and echo
          command: echo $BUILD_COMPLETED
          environment:
            BUILD_COMPLETED: true

          