version: 2.1

jobs:
  build:
    - image: circleci/postgres:11-alpine
      environment:
        POSTGRES_USER: root
        POSTGRES_DB: evernow_test
    - image: node:12-alpine
    steps:
      - checkout
      - run: node --version
      - run: npm i