# version: 2.1

# # What I want to be able to do is
# # call \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat\" -host_arch=amd64 -arch=amd64
# # Which works fine on azure pipelines and over ssh

# orbs:
#   win: circleci/windows@1.0.0

# jobs:
#   installation:
#     docker:
#       - image: win/vs2019
    # steps:
    #   - run:
    #       name: install dotnet
    #       command: |
    #         sudo choco install powershell-core
    #         $PSVersionTable
    #   - run:
    #       name: install dotnet
    #       command: |
    #         sudo choco install dotnetcore-sdk
    #         dotnet --info

# workflows:
#   version: 2
#   build_and_test_all:
#     jobs:
#       - installation

version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - run:
          name: install powershell 6
          command: |
            choco install powershell-core
            New-Item -Path "C:\Program Files\PowerShell\6.0.0\pwsh.exe" -ItemType SymbolicLink -Value "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"
      - run:
          name: check powershell version
          shell: powershell.exe
          command: |
            refreshenv
            $PSVersionTable
      - run:
          name: install dotnet
          command: |
            choco upgrade dotnetcore-sdk
      - run:
          name: check dotnet version
          command: |
            dotnet --info