version: 2.1

# What I want to be able to do is
# call \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat\" -host_arch=amd64 -arch=amd64
# Which works fine on azure pipelines and over ssh

orbs:
  win: circleci/windows@1.0.0

jobs:
  installation:
    docker:
      - image: circleci/windows-server-2019:201908-08
    steps:
      - run:
          name: install dotnet
          command: |
            choco install powershell-core
            $PSVersionTable
      - run:
          name: install dotnet
          command: |
            choco install dotnetcore-sdk
            dotnet --info

workflows:
  version: 2
  build_and_test_all:
    jobs:
      - installation