version: 2.1
parameters:
  BUILD_COMPLETED:
    type: boolean
    default: true
workflows:
  version: 2
  test:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: circleci/node:11.1.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: store env and echo
          command: |
            echo "========"
            echo $BUILD_COMPLETED
            echo "========"
            echo $BUILD_WHAT
            echo "========"
            echo $WTF
          environment:
            BUILD_WHAT: false
            WTF: '1'

          