version: 2.1

jobs:
  build:
    docker:
      - image: circleci/postgres:11-alpine
      - image: node:12-alpine
      environment:
        POSTGRES_USER: root
        POSTGRES_DB: evernow_test
        TIMESTAMP: $date
    steps:
      - checkout
      - run: node --version
      - run: echo $TIMESTAMP