version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    environment:
        TIMESTAMP: now
    steps:
      - checkout
      - run: node --version
      - run: echo $TIMESTAMP