version: 2.0
workflows:
  version: 2
  test:
    jobs:
      - show-chrome-version
jobs:
  show-chrome-version:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - run:
          command: |
            google-chrome --version